[tool.pylint]
max-line-length = 120
disable = [
    "C0111",  # missing-docstring,
    "W1203",  # Use lazy % or .format() formatting in logging functions
]

[tool.mypy]
ignore_missing_imports = true
strict = true

