[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pylint]
max-line-length = 120
disable = [
    "C0111",  # missing-docstring,
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
    "W1203",  # Use lazy % or .format() formatting in logging functions
    "R1723",  # no-else-break
    "R1705",  # no-else-return
    "R0801",  # duplicate-code (we see this in tests)
    "W0212",  # protected-access
]

[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.pylint.main]
ignore = [
    "node_modules",
    ".ipynb_checkpoints"
]
