global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'ray'
    file_sd_configs:
      - files:
        - '/tmp/ray/prom_metrics_service_discovery.json'
    # Fallback static config if service discovery file isn't available
    static_configs:
      - targets: ['rgi-env:8265']
    metrics_path: '/metrics' 